import puppeteer from "puppeteer";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 });
await p.goto("https://floorrescue.vercel.app/", { waitUntil: "networkidle2", timeout: 60000 });
await p.evaluate(() => { sessionStorage.clear(); localStorage.clear(); });
await p.evaluate(() => [...document.querySelectorAll("h2")].find((h) => h.textContent.includes("Every system we install"))?.scrollIntoView({ block: "start" }));
await sleep(2000);
await p.screenshot({ path: "temporary-screenshots/v7-systems.jpg", type: "jpeg", quality: 78 });
await p.evaluate(() => document.getElementById("problem-finder")?.scrollIntoView({ block: "center" }));
await sleep(800);
await p.type("#problem-finder", "my floor is breaking");
await sleep(500);
await p.screenshot({ path: "temporary-screenshots/v7-finder.jpg", type: "jpeg", quality: 78 });
await p.setViewport({ width: 1366, height: 900 });
await p.evaluate(() => [...document.querySelectorAll("h2")].find((h) => h.textContent.includes("A floor is layers"))?.scrollIntoView({ block: "start" }));
await sleep(3000);
await p.screenshot({ path: "temporary-screenshots/v7-layers.jpg", type: "jpeg", quality: 78 });
await b.close();
