import puppeteer from "puppeteer";
const BASE = "http://localhost:3100";
const OUT = "temporary-screenshots/levels";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1366, height: 900 });
await p.goto(BASE + "/commercial/hotel-hospitality", { waitUntil: "networkidle2" });
await p.evaluate(() => [...document.querySelectorAll("section")].find((s) => /Walk Your/i.test(s.textContent.slice(0, 40)))?.scrollIntoView({ block: "start" }));
await sleep(2200);
await p.screenshot({ path: `${OUT}/walk-hotel.jpg`, type: "jpeg", quality: 70 });
await p.goto(BASE + "/systems/metallic-epoxy", { waitUntil: "networkidle2" });
await p.evaluate(() => window.scrollTo(0, 420));
await sleep(1200);
await p.screenshot({ path: `${OUT}/system.jpg`, type: "jpeg", quality: 70 });
await b.close();
